version: "2.3"
# This server profile used as basis for ping-devop docker-launch
#-------------------------------------------------------------------------------------
#- Ping Identity PingFederate getting started demo
#-
#-                +---------------+
#-                | PingFederate  |
#-                +---------------+
#-
#- To access PingFederate Console
#-
#-    https://localhost:9999/pingfederate/app
#-
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------
services:
  pingfederate:
    #image: docker.io/pingidentity/pingfederate:edge
    image: docker.corp.pingidentity.com:5300/pingfederate:10.3.0-rhel7_7.9-rl11-x86_64-edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/leggettc/bc-fips
      - SERVER_PROFILE_PATH=server-profile/pingfederate
      - PF_ENGINE_PRIVATE_PORT_HTTPS=9031
      - PF_ENGINE_PUBLIC_PORT_HTTPS=9031
      - PF_SECONDARY_HTTPS_PORT=9032
      - PF_LOG_LEVEL=DEBUG
      - PF_HSM_MODE=BCFIPS
      - PF_HSM_HYBRID=false
      - PF_BC_FIPS_APPROVED_ONLY=false
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9031:9031"
      - "9999:9999"
      - "9032:9032"
    networks:
      - pingnet
networks:
  pingnet: