version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingFederate getting started demo
#-
#-                +---------------+
#-                | PingFederate  |
#-                +---------------+
#-
#- To access PingFederate Console
#-
#-    https://localhost:9999/pingfederate/app
#-
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingfederate:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - PF_HSM_MODE=BCFIPS
      - PF_LOG_LEVEL=DEBUG
      #- SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      #- SERVER_PROFILE_PATH=getting-started/pingfederate 
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
    volumes:
      - ${HOME}/projects/devops/bc-fips/server-profile/pingfederate/instance:/opt/in/instance
      - ${HOME}/projects/devops/bc-fips/server-profile/java/security/java.security:/opt/java/conf/security/java.security
      - ${HOME}/projects/devops/bc-fips/server-profile/java/security/java.security:/opt/java/conf/security/openjsse.security
    #  - /Users/cleggett/projects/devops/bc-fips/volumes/java/out:/opt/java:ro
    #  - pingfederate-out:/opt/out
    #  - /Users/cleggett/projects/devops/pingidentity-server-profiles/getting-started/pingfederate:/opt/in

networks:
  pingnet:

volumes:
  pingfederate-in:
#  pingfederate-in:
